import type { Chunk } from "./types";

const STOP = new Set([
  "the", "and", "for", "with", "that", "this", "from", "are", "was", "were", "his", "her",
  "you", "your", "about", "what", "when", "where", "which", "who", "how", "does", "did",
  "can", "into", "onto", "over", "than", "then", "them", "they", "have", "has", "had",
  "not", "but", "any", "all", "also",
]);

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9+.#/]+/g, " ")
    .split(/\s+/)
    .map((t) => t.trim())
    .filter((t) => t.length > 1 && !STOP.has(t));
}

export function retrieveLocal(chunks: Chunk[], question: string, k = 5): { title: string; text: string; id: string; score: number }[] {
  const qTokens = tokenize(question);
  const docs = chunks.map((chunk) => {
    const tokens = tokenize(`${chunk.title} ${chunk.text} ${chunk.tags.join(" ")}`);
    const tf = new Map<string, number>();
    for (const t of tokens) tf.set(t, (tf.get(t) || 0) + 1);
    return { chunk, tf };
  });

  // Rare words decide the match; mirrors the server scorer in apps/api/src/retrieve.ts.
  const idf = new Map<string, number>();
  for (const q of new Set(qTokens)) {
    const df = docs.reduce((n, d) => n + (d.tf.has(q) ? 1 : 0), 0);
    idf.set(q, Math.log(1 + docs.length / (1 + df)));
  }

  const scored = docs.map(({ chunk, tf }) => {
    let score = 0;
    for (const q of qTokens) {
      const weight = idf.get(q) || 0;
      const f = tf.get(q) || 0;
      if (f > 0) score += (1 + Math.log(1 + f)) * weight;
      if (chunk.title.toLowerCase().includes(q)) score += 2.4 * weight;
      if (chunk.tags.some((tag) => tag.toLowerCase().includes(q))) score += 1.4 * weight;
    }
    return { id: chunk.id, title: chunk.title, text: chunk.text, score };
  });
  const hits = scored.filter((s) => s.score > 0).sort((a, b) => b.score - a.score);
  if (hits.length) return hits.slice(0, k);
  return chunks.filter((c) => c.id === "summary" || c.id === "identity").map((c) => ({
    id: c.id,
    title: c.title,
    text: c.text,
    score: 0,
  }));
}

export function extractiveLocal(question: string, hits: { title: string; text: string }[]): string {
  const lines = [
    "The live AI demo runs on Peter's workstation — ask him for the live link. This answer is pulled straight from the curated corpus, not generated by a model.",
    "",
    `Question: ${question}`,
    "",
  ];
  for (const hit of hits) {
    lines.push(`## ${hit.title}`);
    lines.push(hit.text);
    lines.push("");
  }
  return lines.join("\n");
}
